#FROM maven:3.8.3-openjdk-17 as MAVEN_BUILD
#WORKDIR /build
#COPY pom.xml .
#COPY src ./src
#RUN mvn package -Dmaven.test.skip=true

#FROM openjdk:17.0.2
#WORKDIR /app
#ARG JAR_FILE=*.jar
#COPY --from=MAVEN_BUILD /build/target/${JAR_FILE} ./app.jar
#EXPOSE 8080
#CMD ["java", "-jar", "app.jar"]

FROM openjdk:17.0.2
WORKDIR /app
ARG JAR_FILE=*.jar
COPY ./target/${JAR_FILE} ./app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]


# docker build -t test_app_basic -f ./Dockerfile-basic .