#FROM maven:3.8.3-openjdk-17 as MAVEN_BUILD
#WORKDIR /build
#COPY pom.xml .
#COPY src ./src
#RUN mvn package -Dmaven.test.skip=true

#FROM openjdk:17.0.2 as JAR_EXTRACT
#WORKDIR /app
#ARG JAR_FILE=*.jar
#COPY --from=MAVEN_BUILD /build/target/${JAR_FILE} ./app.jar
#RUN java -Djarmode=layertools -jar ./app.jar extract

FROM openjdk:17.0.2 as JAR_EXTRACT
WORKDIR /app
ARG JAR_FILE=*.jar
COPY ./target/${JAR_FILE} ./app.jar
RUN java -Djarmode=layertools -jar ./app.jar extract

FROM openjdk:17.0.2
WORKDIR /application
COPY --from=JAR_EXTRACT /app/dependencies ./
COPY --from=JAR_EXTRACT /app/spring-boot-loader ./
COPY --from=JAR_EXTRACT /app/snapshot-dependencies ./
COPY --from=JAR_EXTRACT /app/application ./
ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher"]

# java -Djarmode=layertools -jar ./target/spring-boot-docker-test-0.0.1-SNAPSHOT.jar list
# docker build -t test_app_layered -f ./Dockerfile-layered .